# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MangaReader3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangaReader3
  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'Erik'
  pod 'SwiftSoup'
  pod 'Kingfisher', '~> 5.0'



end
